export const colors = {
    'dark': {
        clearWhite: '#FFFFFF',
        mutedWhite: '#FCFCFC',
        lightSilver: '#E4E6E8',
        silver: '#BDBFC1',
        darkSilver: '#5F6770',
        brightOrange: '#FF4D07',
        mutedOrange: '#F25C21',
        brightLightBlue: '#1EBCFF',
        superLightBlue: '#D3EBF8',
        lightBlue: '#91C4E6',
        brightBlue: '#008CFF',
        blue: '#0079C2',
        mutedBlue: '#009EE1',
        darkBlue: '#0A5088',
        superDarkBlue: '#043B6B',
        hoveredStroke: '#E9F7FF',
    },
    'light': {
        clearWhite: '#FFFFFF',
        mutedWhite: '#FCFCFC',
        lightSilver: '#E4E6E8',
        silver: '#BDBFC1',
        darkSilver: '#5F6770',
        brightOrange: '#FF4D07',
        mutedOrange: '#F25C21',
        brightLightBlue: '#1EBCFF',
        superLightBlue: '#D3EBF8',
        lightBlue: '#91C4E6',
        brightBlue: '#008CFF',
        blue: '#0079C2',
        mutedBlue: '#009EE1',
        darkBlue: '#0A5088',
        superDarkBlue: '#043B6B',
        hoveredStroke: '#E9F7FF',
    }
}